### ISSUE TITLE
Where I can get node with quic enable?

### ISSUE THREAD

**Issue by OmerHerera** [trivikr/node-http-servers#1]
Without building my own node, where I can get a node version with quic enable?

**Comment by trivikr** [comment]
The only way to get node with QUIC enabled right now is to build it yourself.

QUIC is under development at https://GitHub.com/nodejs/quic and it's not being released. It'll be merged in https://GitHub.com/nodejs/node at some point

**Comment by OmerHerera** [comment]
😢 - Ok, Thanks for your answer, do you have any documentation/tutorial steps expect of this documentation:
here https://github.com/nodejs/quic#building-nodejs
It's been difficult for me to build, I can't build it and of course, the tests are failing because was build successfully.
Do you have tips on how to set up your local environment, I'm guessing the first time it's hard.
After you answer me, you can close the issue.
Thanks a lot for help/time

**Comment by trivikr** [comment]
I have a PR open at https://github.com/nodejs/quic/pull/175 to add `--experimental-quic` during configure stage, but we planned to create a pinned issue instead. The reason being QUIC is still experimental.

You can refer diff in the PR, while the pinned issue is created.

**Comment by trivikr** [comment]
An issue with instructions for new contributors was created at https://github.com/nodejs/quic/issues/183

@OmerHerera Do comment on it, if you're still facing problems building Node.js with QUIC enabled.

**Comment by trivikr** [comment]
Also referenced the issue from README in commit https://github.com/trivikr/node-http-servers/commit/f5a96e6cc1ad441b3ba5687c914f2ea3f8414369
